version: "3.12"

services:
  tgebotz:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      BOT_TOKEN: "YOUR_BOT_TOKEN"
      API_ID: "YOUR_API_ID"
      API_HASH: "YOUR_API_HASH"
      CHANNELS: "YOUR_CHANNELS"
      ADMINS: "YOUR_ADMINS"
      LOG_CHANNEL: "YOUR_LOG_CHANNEL"
      DATABASE_NAME: "YOUR_DATABASE_NAME"
      DATABASE_URI: "YOUR_DATABASE_URI"
      KOYEB: "1"              # Detect Koyeb deployment
      HAS_SSL: "1"            # Optional: HTTPS
      FQDN: "tgebotz.koyeb.app"
      PING_INTERVAL: "300"   # seconds (5 minutes)
    volumes:
      - .:/app
    command: python3 bot.py
